#!/usr/bin/env bash

set -euo pipefail

declare -r REPO_ROOT="$(git rev-parse --show-toplevel)"
declare -r PACKAGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export MY_LIB_DIR="$REPO_ROOT/shell/dotfiles/.local/share/my/lib"
export PATH="$REPO_ROOT/shell/dotfiles/.local/share/my/bin:$PATH"

#source "$REPO_ROOT/install.d/lib/envs.sh"
source "$MY_LIB_DIR/bash/installer.sh"

# Fires when the script exits. Prints debug info.
completed() {

  (( LOG_LEVEL >= 8 )) && {
    echo 
    debug_badge "$(basename $0)"
    debug "OPTIONS: "
    echo "$(printf '%d = 0x%x = ' "$OPTIONS" "$OPTIONS")$(to_binary $OPTIONS)" | indent
    for opt in $(get_options_str "${OPTIONS[@]}"); do echo "$opt" | indent; done;
    debug "SEARCH_PATH: $SEARCH_PATH"
    debug "MODULES: "
    for module in "${MODULES[@]}"; do echo "$module" | indent; done;
    debug_badge "ENV"
    debug "LOG_LEVEL: $LOG_LEVEL"
    debug "MY_LIB_DIR: $MY_LIB_DIR"
    debug "REPO_ROOT: $REPO_ROOT"
  }
}

# GLOBALS
SEARCH_PATH="$PACKAGE_ROOT/install.d"
PREFIX=my
EXT="*.sh"

trap completed EXIT

# User can install everything (except extra modules)
# User can install a single PACKAGE
#  - User can install everyting (except extra modules)
#  - User can select modules to install
#  - User can select extra modules to install
while [[ "$#" -gt 0 ]]; do 
  case "$1" in 
    -h|--help) ACTION="HELP"; shift; ;;
    -i|--install) OPTIONS=$(( OPTIONS | OPT_INSTALL )); shift; ;;
    -n|--dryrun) OPTIONS=$(( OPTIONS | OPT_DRYRUN )); shift; ;;
    -u|--uninstall) OPTIONS=$(( OPTIONS | OPT_UNINSTALL )); shift ;;
    -s|--select) OPTIONS=$(( OPTIONS | OPT_SELECT )); shift ;;
    -x|--extra) OPTIONS=$(( OPTIONS | OPT_EXTRA )); shift ;;
    -v|--verbose) OPTIONS=$(( OPTIONS | OPT_VERBOSE )); shift ;;
    *) break ;;
  esac
done

(( $OPTIONS & $OPT_EXTRA )) && SEARCH_PATH+="/extra"

validate_options $OPTIONS

if (( $OPTIONS & $OPT_SELECT )); then
  mapfile -t MODULES < <(sys-select-items -m "$SEARCH_PATH/$EXT")
else 
  mapfile -t MODULES < <(sys-list-items "$SEARCH_PATH/$EXT")
fi

action="$(get_action $OPTIONS)"
package_badge "$action" "$(basename $PACKAGE_ROOT):" " ${action}ing ${#MODULES[@]} modules..."

process_modules $OPTIONS "${MODULES[@]}"
