#!/usr/bin/env bash

set -euo pipefail

declare -r REPO_ROOT="$(git rev-parse --show-toplevel)"

#source "$REPO_ROOT/install.d/lib/envs.sh"
source "$MY_LIB_DIR/bash/installer.sh"

# Fires when the script exits. Prints debug info.
completed() {

  (( LOG_LEVEL >= 8 )) && {
    echo 
    debug_badge "$(basename $0)"
    debug "OPTIONS: $(printf '%d = 0x%x = ' "$OPTIONS" "$OPTIONS")$(to_binary $OPTIONS)"
    debug "OPT_EXTRA: $(( OPTIONS & OPT_EXTRA ))"
    debug "OPT_INSTALL: $(( OPTIONS & OPT_INSTALL ))"
    debug "OPT_SELECT: $(( OPTIONS & OPT_SELECT ))"
    debug "OPT_UNINSTALL: $(( OPTIONS & OPT_UNINSTALL ))"
    debug "SEARCH_PATH: $SEARCH_PATH"
    debug "MODULES: "
    for module in "${MODULES[@]}"; do echo "$module" | indent; done;

    echo 
    debug_badge "ENV"
    debug "LOG_LEVEL: $LOG_LEVEL"
    debug "MY_LIB_DIR: $MY_LIB_DIR"
    debug "REPO_ROOT: $REPO_ROOT"
  }
}

# GLOBALS
SEARCH_PATH=

trap completed EXIT

while [[ "$#" -gt 0 ]]; do 
  case "$1" in 
    -h|--help) ACTION="HELP"; shift; ;;
    -i|--install) OPTIONS=$(( OPTIONS | OPT_INSTALL )); shift; ;;
    -u|--uninstall) OPTIONS=$(( OPTIONS | OPT_UNINSTALL )); shift ;;
    -s|--select) OPTIONS=$(( OPTIONS | OPT_SELECT )); shift ;;
    -x|--extra) OPTIONS=$(( OPTIONS | OPT_EXTRA )); shift ;;
    -v|--verbose) OPTIONS=$(( OPTIONS | OPT_VERBOSE )); shift ;;
    *) break ;;
  esac
done

# LOG_LEVEL
(( (OPTIONS & OPT_VERBOSE ) == OPT_VERBOSE )) && { LOG_LEVEL=16; }

# Sanity check
source "./install.d/lib/prerequisites.sh"

# Set search path 
if (( (OPTIONS & OPT_EXTRA) == OPT_EXTRA )); then
  SEARCH_PATH=./install.d/extra/*.sh
  debug "Using extra search path '$SEARCH_PATH'."
else
  SEARCH_PATH="./install.d/*.sh"
  debug "Using default search path '$SEARCH_PATH'."
fi

# Gather modules
if (( (OPTIONS & OPT_SELECT) == OPT_SELECT )); then
  mapfile -t MODULES < <(sys-select-items -m "$SEARCH_PATH")
else
  mapfile -t MODULES < <(sys-list-items "$SEARCH_PATH")
fi

process_modules $OPTIONS "${MODULES[@]}"

