-- ###################################################################
--
-- ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗
-- ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
-- ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
-- ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
-- ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
-- ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝
-- ###################################################################

local optional = require("modules.lib.optional")

require("modules.autostart")
require("modules.inputs")

-- monitors.lua / workspaces.lua are generated by nwg-displays and gitignored;
-- neither exists until nwg-displays has been run once on this machine.
optional.require("monitors", function()
	hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
	hl.notification.create({
		text = "No monitors.lua found — run nwg-displays and save a profile to configure your displays.",
		timeout = 8000,
	})
end)
optional.require("workspaces")

require("modules.windows")
require("modules.looknfeel")
require("modules.layouts")
require("modules.keybinds")
require("modules.applications")
require("modules.envs")
