-- Generated by nwg-displays on 2026-09-09 at 19:28:47. Do not edit manually.

hl.monitor({
    output = "eDP-2",
    mode = "2560x1600@165.0",
    position = "0x0",
    scale = 1.6,
    vrr = 0
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@60.0",
    position = "1600x0",
    scale = 1,
    vrr = 0
})
